# noinspection ComposeUnknownKeys
name: "gallery-pixels-services"

services:
  gallerypixels_pg:
    image: postgres
    restart: always
    container_name: gallerypixels_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gallerypixels_pg_user
      POSTGRES_PASSWORD: strong_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gallerypixels_pg_user" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - gallerypixels_pgdata:/var/lib/postgresql/data

volumes:
  gallerypixels_pgdata:
